default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  min_messages: WARNING
  pool: 5
  timeout: 5000
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: todo_api_dev

test:
  <<: *default
  database: todo_api_test

production:
  <<: *default
  database: todo_api_production
